In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('loan_approve_dataset.csv')

In [3]:
data

,Gender,Marital_Status,Dependents,Education,Self_Employed,Applicant_Income,Loan_Amount,Loan_Term,Cibil_score,Assets,Loan_Status
0,1,1,1,1,0,550000,150000,360,750,500000,1
1,0,0,0,1,0,600000,120000,240,720,400000,1
2,1,1,2,0,1,520000,180000,180,650,300000,0
3,1,1,3,1,0,800000,250000,360,800,700000,1
4,0,0,0,1,1,510000,100000,120,680,350000,0
5,1,1,1,1,0,700000,200000,300,770,600000,1
6,0,1,2,1,0,650000,220000,360,740,550000,1
7,1,0,0,0,1,530000,140000,180,660,250000,0
8,1,1,3,1,0,900000,300000,360,820,800000,1
9,0,0,1,1,0,580000,130000,240,700,450000,1

In [4]:
data.columns

Index(['Gender', 'Marital_Status', 'Dependents', 'Education', 'Self_Employed',
       'Applicant_Income', 'Loan_Amount', 'Loan_Term', 'Cibil_score', 'Assets',
       'Loan_Status'],
      dtype='object')

In [5]:
data.isnull().sum

<bound method DataFrame.sum of    Gender  Marital_Status  Dependents  Education  Self_Employed  \
0   False           False       False      False          False
1   False           False       False      False          False
2   False           False       False      False          False
3   False           False       False      False          False
4   False           False       False      False          False
5   False           False       False      False          False
6   False           False       False      False          False
7   False           False       False      False          False
8   False           False       False      False          False
9   False           False       False      False          False

   Applicant_Income  Loan_Amount  Loan_Term  Cibil_score  Assets  Loan_Status
0             False        False      False        False   False        False
1             False        False      False        False   False        False
2             False        False      False        False   False        False
3             False        False      False        False   False        False
4             False        False      False        False   False        False
5             False        False      False        False   False        False
6             False        False      False        False   False        False
7             False        False      False        False   False        False
8             False        False      False        False   False        False
9             False        False      False        False   False        False  >

In [6]:
data.isnull().sum()

Gender              0
Marital_Status      0
Dependents          0
Education           0
Self_Employed       0
Applicant_Income    0
Loan_Amount         0
Loan_Term           0
Cibil_score         0
Assets              0
Loan_Status         0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
input_data = data.drop(columns=['Loan_Status'])
output_data = data['Loan_Status']

In [9]:
input_data

,Gender,Marital_Status,Dependents,Education,Self_Employed,Applicant_Income,Loan_Amount,Loan_Term,Cibil_score,Assets
0,1,1,1,1,0,550000,150000,360,750,500000
1,0,0,0,1,0,600000,120000,240,720,400000
2,1,1,2,0,1,520000,180000,180,650,300000
3,1,1,3,1,0,800000,250000,360,800,700000
4,0,0,0,1,1,510000,100000,120,680,350000
5,1,1,1,1,0,700000,200000,300,770,600000
6,0,1,2,1,0,650000,220000,360,740,550000
7,1,0,0,0,1,530000,140000,180,660,250000
8,1,1,3,1,0,900000,300000,360,820,800000
9,0,0,1,1,0,580000,130000,240,700,450000

In [10]:
output_data

0    1
1    1
2    0
3    1
4    0
5    1
6    1
7    0
8    1
9    1
Name: Loan_Status, dtype: int64

In [11]:
x_train,x_test,y_train,y_test = train_test_split(input_data,output_data, test_size=0.2)

In [12]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((8, 10), (2, 10), (8,), (2,))

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
x_train_scaled = scaler.fit_transform(x_train)

In [16]:
x_test_scaled = scaler.transform(x_test)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
model = LogisticRegression()

In [19]:
model.fit(x_train_scaled, y_train)

LogisticRegression()

In [20]:
model.score(x_test_scaled, y_test)

1.0

In [22]:
pred_data = pd.DataFrame([['1','1','1','1','0','550000','150000','360','750','1000000']],columns=['Gender','Marital_Status','Dependents','Education','Self_Employed','Applicant_Income','Loan_Amount','Loan_Term','Cibil_score','Assets'])

In [23]:
pred_data = scaler.transform(pred_data)

In [24]:
model.predict(pred_data)

array([1], dtype=int64)

In [25]:
import pickle as pk

In [26]:
pk.dump(model,open('model.pkl','wb'))

In [27]:
pk.dump(scaler,open('scaler.pkl','wb'))